/**
* mcc-g22-api
* Api for the mcc course group 22
*
* The version of the OpenAPI document: 1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.mcc.g22.apiclient.models

import com.mcc.g22.apiclient.models.Status

import com.squareup.moshi.Json
/**
 * 
 * @param status 
 */

data class InlineObject1 (
    @Json(name = "status")
    val status: Status
) 



