/**
* mcc-g22-api
* Api for the mcc course group 22
*
* The version of the OpenAPI document: 1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.mcc.g22.apiclient.models


import com.squareup.moshi.Json
/**
 * 
 * @param name 
 * @param description 
 * @param badgeUrl 
 * @param `private` 
 * @param keywords 
 */

data class Project (
    @Json(name = "name")
    val name: kotlin.String,
    @Json(name = "description")
    val description: kotlin.String,
    @Json(name = "private")
    val `private`: kotlin.Boolean,
    @Json(name = "badgeUrl")
    val badgeUrl: kotlin.String? = null,
    @Json(name = "keywords")
    val keywords: kotlin.Array<kotlin.String>? = null
) 



