/**
* mcc-g22-api
* Api for the mcc course group 22
*
* The version of the OpenAPI document: 1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.mcc.g22.apiclient.models

import com.mcc.g22.apiclient.models.Status

import com.squareup.moshi.Json
/**
 * 
 * @param projectId 
 * @param description 
 * @param status 
 * @param deadline 
 */

data class Task (
    @Json(name = "projectId")
    val projectId: kotlin.String,
    @Json(name = "description")
    val description: kotlin.String,
    @Json(name = "status")
    val status: Status,
    @Json(name = "deadline")
    val deadline: java.time.LocalDateTime
) 



